version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "@tauri-apps/*"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    rebase-strategy: "disabled"
    open-pull-requests-limit: 2
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
    rebase-strategy: "disabled"
