// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IotaNetwork } from "./IotaNetwork";

export interface IotaWallet { address: string, did: string | null, network: IotaNetwork, imported: boolean, did_document_published: boolean, }
