blank_issues_enabled: false
contact_links:
  - name: ObjectID-wallet repository
    url: https://github.com/sdellava/ObjectID-wallet/issues
    about: "Use the repository issues for questions about OIDwallet."
