// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppTheme } from "../profile_settings/AppTheme";
import type { IotaWalletSetup } from "./IotaWalletSetup";

export interface CreateNew { name: string, picture: string, theme: AppTheme, password: string, biometrics_enabled: boolean, iota_wallet?: IotaWalletSetup | null, }
